from django.urls import path
from . import views

urlpatterns = [
    #path('', views.index, name= 'index'),
    # path('login/', views.get_login_view, name='login'),
    # path('postLogin/', views.login_view, name='login'),
    # path('register/', views.get_register_view, name='register'),
    # path('postRegister/', views.register_view, name='register'),
    # path('admin/<int:idUser>', views.admin, name='admin'),
    # path('patient/', views.patient, name='patient'),
    # path('doctor/<int:idUser>', views.doctor, name='doctor'),
    # path('forgetpass/', views.forget_password, name='forgetpass'),
    # path('doctor/<int:idUser>/edit/', views.edit, name='doctor_edit'),
    # #path('doctor/<int:idUser>/edit_view/', views.edit_view, name='doctor_edit'),
    # path('profile_patient/<int:idUser>', views.profile_patient, name='profile_patient'),
    # path('admin_profile/<int:idUser>', views.admin_profile, name='admin_profile'),
    # path('admin_task/<int:idUser>', views.admin_task, name='admin_task'),
    # path('admin_setting/<int:idUser>', views.admin_setting, name='admin_setting'),
    # path('admin_mda/<int:idUser>', views.admin_mda, name='admin_mda'),
    # path('admin_mpa/<int:idUser>', views.admin_mpa, name='admin_mpa'),
    # path('update_user_status/', views.update_user_status, name='update_user_status'),
    # path('update_doctor_status/', views.update_doctor_status, name='update_doctor'),
    # path('admin_eda/<int:idUser>/<int:idd>',views.admin_eda, name='admin_eda'),
    # path('admin_ada/<int:idUser>',views.admin_ada, name='admin_ada'),

    path('', views.get_login_view, name='login'),
    path('loginPost/', views.login_view, name='login'),
    path('register/', views.get_register_view, name='register'),
    path('postRegister/', views.register_view, name='register'),
    path('admin/<int:idUser>', views.admin, name='admin'),
    path('patient/', views.patient, name='patient'),
    path('doctor/<int:idUser>', views.doctor, name='doctor'),
    path('forgetpass/', views.forget_password, name='forgetpass'),
    path('doctor_edit/<int:idUser>', views.doctor_edit, name='doctor_edit'),
    #path('doctor/<int:idUser>/edit_view/', views.edit_view, name='doctor_edit'),
    path('profile_patient/', views.profile_patient, name='profile_patient'),
    path('admin_profile/<int:idUser>', views.admin_profile, name='admin_profile'),
    path('admin_task/<int:idUser>', views.admin_task, name='admin_task'),
    path('admin_setting/<int:idUser>', views.admin_setting, name='admin_setting'),
    path('admin_mda/<int:idUser>', views.admin_mda, name='admin_mda'),
    path('admin_mpa/<int:idUser>', views.admin_mpa, name='admin_mpa'),
    path('update_user_status/', views.update_user_status, name='update_user_status'),
    path('update_doctor_status/', views.update_doctor_status, name='update_doctor'),
    path('admin_eda/<int:idUser>/<int:idd>',views.admin_eda, name='admin_eda'),
    path('admin_ada/<int:idUser>',views.admin_ada, name='admin_ada'),
]