# Generated by Django 4.2.13 on 2024-05-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=500, null=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=500, null=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=50, null=True)),
                ('createdby', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('updatedby', models.IntegerField(blank=True, db_column='UpdatedBy', null=True)),
                ('updateddate', models.DateTimeField(blank=True, db_column='UpdatedDate', null=True)),
            ],
            options={
                'db_table': 'Accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicalrecords',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('bloodtype', models.CharField(blank=True, db_column='BloodType', max_length=5, null=True)),
                ('allergy', models.CharField(blank=True, db_column='Allergy', max_length=500, null=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=50, null=True)),
                ('creadtedby', models.IntegerField(blank=True, db_column='CreadtedBy', null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('updatedby', models.IntegerField(blank=True, db_column='UpdatedBy', null=True)),
                ('updateddate', models.DateTimeField(blank=True, db_column='UpdatedDate', null=True)),
            ],
            options={
                'db_table': 'MedicalRecords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('reason', models.CharField(blank=True, db_column='Reason', max_length=500, null=True)),
                ('symptom', models.CharField(blank=True, db_column='Symptom', max_length=500, null=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=50, null=True)),
                ('createdby', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('updatedby', models.IntegerField(blank=True, db_column='UpdatedBy', null=True)),
                ('updateddate', models.DateTimeField(blank=True, db_column='UpdatedDate', null=True)),
            ],
            options={
                'db_table': 'Meetings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('rolename', models.CharField(blank=True, db_column='RoleName', max_length=50, null=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=50, null=True)),
                ('createdby', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('updatedby', models.IntegerField(blank=True, db_column='UpdatedBy', null=True)),
                ('updateddate', models.DateTimeField(blank=True, db_column='UpdatedDate', null=True)),
            ],
            options={
                'db_table': 'Roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('startshift', models.DateTimeField(blank=True, db_column='StartShift', null=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=50, null=True)),
                ('createdby', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('updatedby', models.IntegerField(blank=True, db_column='UpdatedBy', null=True)),
                ('updateddate', models.DateTimeField(blank=True, db_column='UpdatedDate', null=True)),
            ],
            options={
                'db_table': 'Schedules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=500, null=True)),
                ('birth', models.DateTimeField(blank=True, db_column='Birth', null=True)),
                ('gender', models.BooleanField(blank=True, db_column='Gender', null=True)),
                ('phonenumber', models.CharField(blank=True, db_column='PhoneNumber', max_length=15, null=True)),
                ('nation', models.CharField(blank=True, db_column='Nation', max_length=50, null=True)),
                ('graduation', models.CharField(blank=True, db_column='Graduation', max_length=500, null=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=50, null=True)),
                ('createdby', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('updatedby', models.IntegerField(blank=True, db_column='UpdatedBy', null=True)),
                ('updateddate', models.DateTimeField(blank=True, db_column='UpdatedDate', null=True)),
                ('avatar', models.BinaryField(blank=True, db_column='Avatar', max_length='max', null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
